services:
  ros_noetic:
    image: ros_noetic_custom
    container_name: ros_noetic
    restart: unless-stopped
    stdin_open: false
    tty: false
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ../src:/root/catkin_ws/src
      - ../gazebo_models:/root/.gazebo/models
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ros_home:/root
    devices:
      - /dev/input:/dev/input
      - /dev/dri:/dev/dri
    command: bash -c "sleep infinity"
volumes:
  ros_home:
