
dictitems:
  groups: 
    dictitems:
      groups: 
        state: []
      hue_white_h: 65
      hue_white_l: 18
      hue_yellow_h: 65
      hue_yellow_l: 18
      id: 0
      lightness_white_h: 255
      lightness_white_l: 99
      lightness_yellow_h: 255
      lightness_yellow_l: 99
      name: Default
      parameters: 
        state: []
      parent: 0
      saturation_white_h: 162
      saturation_white_l: 0
      saturation_yellow_h: 162
      saturation_yellow_l: 0
      state: true
      type: ''
    state: []
  hue_white_h: 65
  hue_white_l: 18
  hue_yellow_h: 65
  hue_yellow_l: 18
  lightness_white_h: 255
  lightness_white_l: 99
  lightness_yellow_h: 255
  lightness_yellow_l: 99
  saturation_white_h: 162
  saturation_white_l: 0
  saturation_yellow_h: 162
  saturation_yellow_l: 0
state: []
