
dictitems:
  bottom_x: 150
  bottom_y: 121
  groups: 
    dictitems:
      bottom_x: 150
      bottom_y: 121
      groups: 
        state: []
      id: 0
      name: Default
      parameters: 
        state: []
      parent: 0
      state: true
      top_x: 52
      top_y: 22
      type: ''
    state: []
  top_x: 52
  top_y: 22
state: []
